name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup and run e2e tests
        working-directory: ./frontend
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
